#!/usr/bin/env python

import rospy
import sys

if __name__ == '__main__':
    rospy.init_node('kinect_frames')
    name = rospy.get_param('~name')
    from_pkg = rospy.get_param('~from_pkg', 'openni_launch')
    to_pkg = rospy.get_param('~to_pkg', 'rgbd_launch')
    from_pkg_path = rospy.get_param('~from_pkg_path')
    to_pkg_path = rospy.get_param('~to_pkg_path')

    rospy.logfatal(name + ' has moved to ' + to_pkg + '! ' +
            'Replace \"$(find ' + from_pkg + ')/' + from_pkg_path + '\" ' +
            'with \"$(find ' + to_pkg + ')/' + to_pkg_path + '\". ' +
            'This notice will be removed in ROS Indigo') 

    sys.exit(0)
